### PR TITLE
Add map sensor config

### PR DESCRIPTION
**Pull request by umdreamer**
This PR has implemented these functions:

Add new map configuration to sora_server.
Fix bug: new sensor cannot be loaded correctly in sora_client
Fix bug: cannot load map and vehicles in VSE.
Usesage:

Add new sensor configurations: python toolset/config_generator.py
Add new map configuration: python toolset/map_generator.py
The exmaples are in testMain() and main().
VSE: The same as wise VSE version.
NOTE: The functions only add configurations to mongodb. The actual asset files of sensors and maps should be put into sara_server/asset accordingly.

### CODE REVIEW

**Comment by umdreamer** [comment]
This should be work.

**Comment by YuqiHuai** [comment]
Thank you so much!

**Comment by umdreamer** [comment]
Thank you for the merging. Hope to contribute more for this project.:)

**Comment by abustaoglu** [comment]
hello @umdreamer. i'm trying to import custom map to the mongo db with your script. i'm little bit confused. what should be map_generator.py's input? if  a give an example from the existing maps, this map file include a json file named manifest.json, but this file's attributes are different from your script. i hope the images below will help me explain my question.

Screenshot 2023-02-28 100051

Screenshot 2023-02-28 100410

**Comment by umdreamer** [comment]
@abustaoglu The manifest.json is not the map config file. The map config file is a json generated from wise.svlsimulator.com. 
I just made a new PR for adding new map from bundle file which you don't have to care about the map config file. Have a try if it works for you. Thank you.

**Comment by TianJinJuanQuan** [comment]
hi, @umdreamer can you have add Vehicles method，like map_generator.py

**Pull request merged**
