### PR TITLE
Modified config generaor to put params in DB

### PR DESCRIPTION
**Pull request by seohwan**
There was an error that params were not added when adding custom sensor configuration.

### CODE REVIEW

**Comment by YuqiHuai** [comment]
Thank you for your contribution!

Both `params` and `transform` were checked in `generate_config`, but not checked in `insert_to_vehicle_sensor_index`

This PR added a safe-check in the function `insert_to_vehicle_sensor_index`.

**Comment by YuqiHuai** [comment]
@seohwan Can you provide me a little more context about what those rubis files are? The `rubis_config_generator` looks similar to `config_generator` except the rubis version uses yaml. Should we keep 2 config generators or should we keep just 1 of them?

**Comment by seohwan** [comment]
Hello,
oh, I just wanted to pull-request only one commits(779bcfc2fdb831fa5ece77b6c92173fe15629bb7)
I'll do the pull-request again.
Sorry for the confusion

**Comment by YuqiHuai** [comment]
No worries. Thanks for the contribution!

**Pull request closed without merging**
