### PR TITLE
+ add map from bundle file (environment_MapName)

### PR DESCRIPTION
**Pull request by umdreamer**
Add new map from bundle file. The bundle file is built by the Simulator, i.e., environment_MapName.

Usage:
1. Add new map from bundle file:
```
map_generator = MapGenerator()
bundle_file = 'environment_NewMap'
map_generator.add_map_to_sora_server(bundle_file)
```
2. Add new map from map config file:
```
map_generator = MapGenerator()
map_config_file = 'NewMap_config.json'
map_generator.insert_map_to_db(map_config_file)
```

### CODE REVIEW

**Comment by YuqiHuai** [comment]
@umdreamer thanks for the contribution! These changes look great!

I took a quick look at the code, this handles creating the preview images, correct?

**Comment by umdreamer** [comment]
@YuqiHuai Yes, this code handles everything from the bundle file to create a new map, including server/assets/map, hdmap, previews, and the mongodb data.

**Comment by YuqiHuai** [comment]
@umdreamer great. sounds good! I am glad you know so much about these bundles!

**Comment by abustaoglu** [comment]
hi @umdreamer. thanks for your excellent work. my server has updated after using your script(from bundle), but map.json file doesn't change, so i couldn't load the map with python api. maps and hd_maps files are remains the same. do you have any suggestion?

**Comment by leonzgtee** [comment]
> Add new map from bundle file. The bundle file is built by the Simulator, i.e., environment_MapName.
> 
> Usage:
> 
> 1. Add new map from bundle file:
> 
> ```
> map_generator = MapGenerator()
> bundle_file = 'environment_NewMap'
> map_generator.add_map_to_sora_server(bundle_file)
> ```
> 
> 2. Add new map from map config file:
> 
> ```
> map_generator = MapGenerator()
> map_config_file = 'NewMap_config.json'
> map_generator.insert_map_to_db(map_config_file)
> ```

nice work,but when i try this script, an error occur "zipfile.BadZipFile: File is not a zip file".
i have build my own map via lgsvl simulator, and the output is a binary file instead of a zip file.
what should i do about this,thanks.

**Comment by abustaoglu** [comment]
Hello @umdreamer,

With your custom map generator, db and client is has updated in both ways(bundle and config file).  But when i try to load map using python api, it's not work. Dou you have any suggestion about this?
github_issue

**Comment by umdreamer** [comment]
Do you give the correct map id? It is not the Guid, but the cid. There are different IDs for a map.

**Comment by abustaoglu** [comment]
Hi again @umdreamer,
Yes, i gave the correct id. Here is my steps, maybe we can figure out the problem:

- I have successfully build the SVL's [CubeTown](https://github.com/lgsvl/CubeTown)
cubetown
- Used your map_generator 
script
- Client side updated.
client
- Try to load map using api
github_issue
- Unity outputs for my map
 unity_out
- Unity outputs for already existing maps
normal_console

**Comment by umdreamer** [comment]
It seems that your map resource has some problem. Do you have a look whether the original CubeTown map is the same as your own build version?

image

**Comment by abustaoglu** [comment]
you are right. i tried with the SVL's original [CubeTown](https://github.com/lgsvl/CubeTown) and [SanFrancisco](https://github.com/lgsvl/SanFrancisco) and its worked. actually i don't know why this error show up but i will figure out.

so thanks for kindly reply @umdreamer

**Comment by TianJinJuanQuan** [comment]
Hi @umdreamer,this tool to add map is very good,I have successfully，but can you have add Vehicles from bundle file tools?

**Pull request merged**
