### PR TITLE
Add map and sensor config, local VSE

### PR DESCRIPTION
**Pull request by umdreamer**
This PR has implemented these functions:
* Add new map configuration  to sora_server.
* Fix bug: new sensor cannot be loaded correctly in sora_client
* Fix bug: cannot load map and vehicles in VSE.

Usesage:
* Add new sensor configurations: `python toolset/config_generator.py`
* Add new map configuration: `python toolset/map_generator.py`
The exmaples are in `testMain()` and `main()`. 
* VSE: The same as wise VSE version.

NOTE: The functions only add configurations to mongodb. The actual asset files of sensors and maps should be put into sara_server/asset accordingly.

### CODE REVIEW

**Comment by YuqiHuai** [comment]
Great changes! Thank you so much for contributing!
Before I merge the pull request, I want to quickly confirm with you that, you intended to modify `mongo/setup/global.json` and added a map named "MyNewMap" by Haifeng Zhao, correct?

**Comment by umdreamer** [comment]
> * Great changes! Thank you so much for contributing!
> * Before I merge the pull request, I want to quickly confirm with you that, you intended to modify `mongo/setup/global.json` and added a map named "MyNewMap" by Haifeng Zhao, correct? @umdreamer

The code will add MyNewMap configurations to  the global, map mongodb. The sensor configurations are added into global, vehicles mongodb. The json files shoulbe be only for the intialization that needn't modify. I'll rollback the json file commit.

**Comment by umdreamer** [comment]
It looks like I mess up the commit history. I'll fix it and repull.

**Comment by YuqiHuai** [comment]
ops. my bad, I was just checking if you intended to add that, I think it is still fine to add it. If the commit history is too hard to fix then are you able to roll back to when you originally opened the PR?

**Pull request closed without merging**
